let books = [
  {
    id: 1,
    title: "Clean Code",
    author: "Robert C. Martin",
    description: "A Handbook of Agile Software Craftsmanship.",
    price: 29.99,
    image_url: "https://unsplash.it/200/300?image=1",
  },
  {
    id: 2,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    description: "Your Journey to Mastery.",
    price: 34.99,
    image_url: "https://unsplash.it/200/300?image=2",
  },
  {
    id: 3,
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    description: "Comprehensive textbook on algorithms.",
    price: 89.99,
    image_url: "https://unsplash.it/200/300?image=3",
  },
  {
    id: 4,
    title: "Design Patterns",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    description: "Elements of Reusable Object-Oriented Software.",
    price: 49.99,
    image_url: "https://unsplash.it/200/300?image=4",
  },
  {
    id: 5,
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    description: "Deep dive into JavaScript language.",
    price: 24.99,
    image_url: "https://unsplash.it/200/300?image=5",
  },
  {
    id: 6,
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    description: "A Modern Introduction to Programming.",
    price: 19.99,
    image_url: "https://unsplash.it/200/300?image=6",
  },
  {
    id: 7,
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    description: "Unearthing the excellence in JavaScript.",
    price: 17.99,
    image_url: "https://unsplash.it/200/300?image=7",
  },
  {
    id: 8,
    title: "Refactoring",
    author: "Martin Fowler",
    description: "Improving the design of existing code.",
    price: 39.99,
    image_url: "https://unsplash.it/200/300?image=8",
  },
  {
    id: 9,
    title: "Effective Java",
    author: "Joshua Bloch",
    description: "Best practices for Java programming.",
    price: 44.99,
    image_url: "https://unsplash.it/200/300?image=9",
  },
  {
    id: 10,
    title: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    description: "189 Programming Questions and Solutions.",
    price: 29.99,
    image_url: "https://unsplash.it/200/300?image=10",
  },
  {
    id: 11,
    title: "The Mythical Man-Month",
    author: "Frederick P. Brooks Jr.",
    description: "Essays on software engineering and project management.",
    price: 24.5,
    image_url: "https://unsplash.it/200/300?image=11",
  },
  {
    id: 12,
    title: "Domain-Driven Design",
    author: "Eric Evans",
    description: "Tackling complexity in software design.",
    price: 54.99,
    image_url: "https://unsplash.it/200/300?image=12",
  },
  {
    id: 13,
    title: "Clean Architecture",
    author: "Robert C. Martin",
    description: "A Craftsman's Guide to Software Structure and Design.",
    price: 32.0,
    image_url: "https://unsplash.it/200/300?image=13",
  },
  {
    id: 14,
    title: "Working Effectively with Legacy Code",
    author: "Michael Feathers",
    description: "Techniques to maintain and improve legacy systems.",
    price: 38.75,
    image_url: "https://unsplash.it/200/300?image=14",
  },
  {
    id: 15,
    title: "Code Complete",
    author: "Steve McConnell",
    description: "A Practical Handbook of Software Construction.",
    price: 42.0,
    image_url: "https://unsplash.it/200/300?image=15",
  },
  {
    id: 16,
    title: "Patterns of Enterprise Application Architecture",
    author: "Martin Fowler",
    description: "Guidance on enterprise application architecture patterns.",
    price: 48.99,
    image_url: "https://unsplash.it/200/300?image=16",
  },
  {
    id: 17,
    title: "The Clean Coder",
    author: "Robert C. Martin",
    description: "A Code of Conduct for Professional Programmers.",
    price: 27.99,
    image_url: "https://unsplash.it/200/300?image=17",
  },
  {
    id: 18,
    title: "Soft Skills",
    author: "John Sonmez",
    description: "The software developer's life manual.",
    price: 22.95,
    image_url: "https://unsplash.it/200/300?image=18",
  },
  {
    id: 19,
    title: "Continuous Delivery",
    author: "Jez Humble, David Farley",
    description:
      "Reliable software releases through build, test, and deployment automation.",
    price: 40.0,
    image_url: "https://unsplash.it/200/300?image=19",
  },
  {
    id: 20,
    title: "Introduction to the Theory of Computation",
    author: "Michael Sipser",
    description: "Foundations of theoretical computer science.",
    price: 69.99,
    image_url: "https://unsplash.it/200/300?image=20",
  },
  {
    id: 21,
    title: "Refactoring: Improving the Design of Existing Code",
    author: "Martin Fowler",
    description: "A guide to refactoring code to improve its design.",
    price: 45.99,
    image_url: "https://unsplash.it/200/300?image=21",
  },
  {
    id: 22,
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    description:
      "Classic book introducing design patterns in software engineering.",
    price: 55.0,
    image_url: "https://unsplash.it/200/300?image=22",
  },
  {
    id: 23,
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    description: "Unearthing the best features of JavaScript.",
    price: 25.5,
    image_url: "https://unsplash.it/200/300?image=23",
  },
  {
    id: 24,
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    description: "Deep dive into JavaScript core mechanisms.",
    price: 35.0,
    image_url: "https://unsplash.it/200/300?image=24",
  },
  {
    id: 25,
    title: "Effective Java",
    author: "Joshua Bloch",
    description: "Best practices for the Java platform.",
    price: 47.75,
    image_url: "https://unsplash.it/200/300?image=25",
  },
  {
    id: 26,
    title: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    description: "189 programming questions and solutions.",
    price: 39.99,
    image_url: "https://unsplash.it/200/300?image=26",
  },
  {
    id: 27,
    title: "The Art of Computer Programming",
    author: "Donald E. Knuth",
    description: "Comprehensive monograph on computer programming algorithms.",
    price: 190.0,
    image_url: "https://unsplash.it/200/300?image=27",
  },
  {
    id: 28,
    title: "Head First Design Patterns",
    author: "Eric Freeman, Elisabeth Robson",
    description: "A brain-friendly guide to design patterns.",
    price: 44.5,
    image_url: "https://unsplash.it/200/300?image=28",
  },
  {
    id: 29,
    title: "Introduction to Algorithms",
    author:
      "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    description: "Widely used textbook for algorithms.",
    price: 80.0,
    image_url: "https://unsplash.it/200/300?image=29",
  },
  {
    id: 31,
    title: "Domain-Driven Design",
    author: "Eric Evans",
    description: "Tackling complexity in software design.",
    price: 55.0,
    image_url: "https://unsplash.it/200/300?image=31",
  },
  {
    id: 32,
    title: "Programming Pearls",
    author: "Jon Bentley",
    description: "Classic book with programming problems and solutions.",
    price: 34.99,
    image_url: "https://unsplash.it/200/300?image=32",
  },
  {
    id: 33,
    title: "Soft Skills",
    author: "John Sonmez",
    description: "The software developer's life manual.",
    price: 22.95,
    image_url: "https://unsplash.it/200/300?image=33",
  },
  {
    id: 34,
    title: "Continuous Delivery",
    author: "Jez Humble, David Farley",
    description:
      "Reliable software releases through build, test, and deployment automation.",
    price: 40.0,
    image_url: "https://unsplash.it/200/300?image=34",
  },
  {
    id: 35,
    title: "Working Effectively with Legacy Code",
    author: "Michael Feathers",
    description: "Techniques to maintain and improve legacy systems.",
    price: 38.75,
    image_url: "https://unsplash.it/200/300?image=35",
  },
  {
    id: 36,
    title: "Code Complete",
    author: "Steve McConnell",
    description: "A Practical Handbook of Software Construction.",
    price: 42.0,
    image_url: "https://unsplash.it/200/300?image=36",
  },
  {
    id: 37,
    title: "The Clean Coder",
    author: "Robert C. Martin",
    description: "A Code of Conduct for Professional Programmers.",
    price: 27.99,
    image_url: "https://unsplash.it/200/300?image=37",
  },
  {
    id: 38,
    title: "Patterns of Enterprise Application Architecture",
    author: "Martin Fowler",
    description: "Guidance on enterprise application architecture patterns.",
    price: 48.99,
    image_url: "https://unsplash.it/200/300?image=38",
  },
  {
    id: 39,
    title: "Refactoring",
    author: "Martin Fowler",
    description: "Improving the design of existing code.",
    price: 39.99,
    image_url: "https://unsplash.it/200/300?image=39",
  },
  {
    id: 40,
    title: "Introduction to the Theory of Computation",
    author: "Michael Sipser",
    description: "Foundations of theoretical computer science.",
    price: 69.99,
    image_url: "https://unsplash.it/200/300?image=40",
  },
  {
    id: 41,
    title: "The Mythical Man-Month",
    author: "Frederick P. Brooks Jr.",
    description: "Essays on software engineering and project management.",
    price: 24.5,
    image_url: "https://unsplash.it/200/300?image=41",
  },
  {
    id: 42,
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    description: "Unearthing the excellence in JavaScript.",
    price: 17.99,
    image_url: "https://unsplash.it/200/300?image=42",
  },
  {
    id: 43,
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    description: "A Modern Introduction to Programming.",
    price: 19.99,
    image_url: "https://unsplash.it/200/300?image=43",
  },
  {
    id: 44,
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    description: "Deep dive into JavaScript language.",
    price: 24.99,
    image_url: "https://unsplash.it/200/300?image=44",
  },
  {
    id: 45,
    title: "Clean Code",
    author: "Robert C. Martin",
    description: "A Handbook of Agile Software Craftsmanship.",
    price: 29.99,
    image_url: "https://unsplash.it/200/300?image=45",
  },
  {
    id: 46,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    description: "Your Journey to Mastery.",
    price: 34.99,
    image_url: "https://unsplash.it/200/300?image=46",
  },
  {
    id: 47,
    title: "Code Complete",
    author: "Steve McConnell",
    description: "A Practical Handbook of Software Construction.",
    price: 42.0,
    image_url: "https://unsplash.it/200/300?image=47",
  },
  {
    id: 48,
    title: "Design Patterns",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    description: "Elements of Reusable Object-Oriented Software.",
    price: 49.99,
    image_url: "https://unsplash.it/200/300?image=48",
  },
  {
    id: 49,
    title: "Refactoring",
    author: "Martin Fowler",
    description: "Improving the design of existing code.",
    price: 39.99,
    image_url: "https://unsplash.it/200/300?image=49",
  },
  {
    id: 50,
    title: "Effective Java",
    author: "Joshua Bloch",
    description: "Best practices for Java programming.",
    price: 44.99,
    image_url: "https://unsplash.it/200/300?image=50",
  },
];

module.exports = { books };
